import { hrService } from './hrService';
import { Attendance, EmployeeAttendanceSummary } from '../types';

export const emailService = {
  /**
   * Standardized endpoint for attendance summaries.
   * Formats and queues a professional Attendance Audit Report.
   * @param subjectSuffix Optional suffix for batched emails (e.g. " [Part 1/3]")
   */
  async sendDailyAttendanceSummary(recipientEmail: string, attendance: Attendance[], subjectSuffix: string = '') {
    if (attendance.length === 0) {
      throw new Error("Cannot send report: No attendance records found for the selected period.");
    }

    console.log(`[emailService] Preparing Attendance Audit for: ${recipientEmail} with ${attendance.length} records.`);

    // Get date range from records if possible
    const dates = attendance.map(a => a.date).sort();
    const rangeStr = dates.length > 1 
      ? `${dates[0]} to ${dates[dates.length - 1]}`
      : dates[0] || new Date().toISOString().split('T')[0];

    const sortedAttendance = [...attendance].sort((a, b) => 
      (a.employeeName || '').localeCompare(b.employeeName || '')
    );

    // Optimized Row Generation (Minified HTML)
    const rows = sortedAttendance.map((a, index) => {
      const rowClass = index % 2 === 0 ? 'r0' : 'r1';
      const statusClass = `s-${a.status}`;
      // Truncate name if too long to save space
      const name = (a.employeeName || 'Unknown').substring(0, 20);
      
      return `<tr class="${rowClass}"><td class="d">${name}</td><td class="d m">${a.checkIn || '-'}</td><td class="d m">${a.checkOut || '-'}</td><td class="d r"><span class="b ${statusClass}">${a.status.substring(0,3)}</span></td></tr>`;
    }).join('');

    // Minified HTML Structure with embedded CSS
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #1e293b; font-size: 12px; }
          .w { max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; }
          .h { background: #0f172a; color: white; padding: 15px; text-align: center; }
          .h h1 { margin: 0; font-size: 16px; text-transform: uppercase; letter-spacing: 1px; }
          .h p { margin: 5px 0 0; font-size: 10px; color: #94a3b8; }
          table { width: 100%; border-collapse: collapse; }
          th { background: #f1f5f9; padding: 8px; font-size: 10px; text-align: left; text-transform: uppercase; color: #64748b; }
          .d { padding: 8px; border-bottom: 1px solid #f1f5f9; }
          .m { font-family: monospace; color: #475569; }
          .r { text-align: right; }
          .b { padding: 2px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; }
          .r0 { background: #ffffff; }
          .r1 { background: #f8fafc; }
          .s-LATE { color: #d97706; background: #fef3c7; }
          .s-ABSENT { color: #dc2626; background: #fee2e2; }
          .s-PRESENT { color: #059669; background: #d1fae5; }
          .f { background: #f8fafc; padding: 10px; text-align: center; font-size: 9px; color: #94a3b8; border-top: 1px solid #e2e8f0; }
        </style>
      </head>
      <body>
        <div class="w">
          <div class="h">
            <h1>Attendance Audit</h1>
            <p>${rangeStr} • ${attendance.length} Records${subjectSuffix}</p>
          </div>
          <table>
            <tr><th>Name</th><th>In</th><th>Out</th><th class="r">Stat</th></tr>
            ${rows}
          </table>
          <div class="f">Generated by Pixenox • Part of secure audit trail</div>
        </div>
      </body>
      </html>
    `.replace(/\s+/g, ' ').trim(); // Simple minification

    try {
      const result = await hrService.sendCustomEmail({ 
        recipientEmail, 
        subject: `[Report] ${rangeStr}${subjectSuffix}`,
        html,
        type: 'SYSTEM_REPORT'
      });
      console.log("[emailService] Success queuing email:", result);
      return result;
    } catch (err) {
      console.error("[emailService] Error dispatching to hrService:", err);
      throw err;
    }
  },

  /**
   * Sends an employee-organized attendance summary report.
   * Groups by employee with Present, Absent, Late, Leave counts and attendance %.
   */
  async sendEmployeeSummaryReport(
    recipientEmail: string,
    summaries: EmployeeAttendanceSummary[],
    periodLabel: string,
    dateRange: string
  ) {
    if (summaries.length === 0) {
      throw new Error("Cannot send report: No employee summary data for the selected period.");
    }

    console.log(`[emailService] Preparing Employee Summary for: ${recipientEmail} with ${summaries.length} employees.`);

    // Build table rows
    const rows = summaries.map((s, i) => {
      const rowClass = i % 2 === 0 ? 'r0' : 'r1';
      const pctColor = s.attendancePercentage >= 90 ? 'c-g' : s.attendancePercentage >= 75 ? 'c-a' : 'c-r';
      return (
        `<tr class="${rowClass}">` +
        `<td class="d">${s.employeeName.substring(0, 25)}</td>` +
        `<td class="d c">${s.department.substring(0, 15)}</td>` +
        `<td class="d r">${s.totalWorkingDays}</td>` +
        `<td class="d r g">${s.presentDays}</td>` +
        `<td class="d r r">${s.absentDays}</td>` +
        `<td class="d r a">${s.lateDays}</td>` +
        `<td class="d r b">${s.leaveDays}</td>` +
        `<td class="d r"><span class="${pctColor}">${s.attendancePercentage}%</span></td>` +
        `</tr>`
      );
    }).join('');

    // Summary stats
    const totalEmployees = summaries.length;
    const totalPresent = summaries.reduce((s, e) => s + e.presentDays, 0);
    const totalAbsent = summaries.reduce((s, e) => s + e.absentDays, 0);
    const totalLate = summaries.reduce((s, e) => s + e.lateDays, 0);
    const totalLeave = summaries.reduce((s, e) => s + e.leaveDays, 0);
    const avgAttendance = Math.round(
      summaries.reduce((s, e) => s + e.attendancePercentage, 0) / totalEmployees
    );

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #1e293b; font-size: 12px; }
          .w { max-width: 700px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; }
          .h { background: #0f172a; color: white; padding: 15px; text-align: center; }
          .h h1 { margin: 0; font-size: 16px; text-transform: uppercase; letter-spacing: 1px; }
          .h p { margin: 5px 0 0; font-size: 10px; color: #94a3b8; }
          .s { background: #f8fafc; padding: 10px; }
          .stat { display: inline-block; padding: 6px 14px; margin: 4px; border-radius: 6px; font-size: 10px; font-weight: bold; }
          .st-p { background: #d1fae5; color: #065f46; }
          .st-a { background: #fee2e2; color: #991b1b; }
          .st-l { background: #fef3c7; color: #92400e; }
          .st-lv { background: #dbeafe; color: #1e40af; }
          table { width: 100%; border-collapse: collapse; }
          th { background: #f1f5f9; padding: 8px; font-size: 9px; text-align: left; text-transform: uppercase; color: #64748b; }
          .d { padding: 7px 6px; border-bottom: 1px solid #f1f5f9; font-size: 10px; }
          .r { text-align: center; }
          .c { text-align: center; color: #64748b; font-size: 9px; }
          .r0 { background: #ffffff; }
          .r1 { background: #f8fafc; }
          .g { color: #059669; font-weight: bold; }
          .r { color: #dc2626; font-weight: bold; }
          .a { color: #d97706; font-weight: bold; }
          .b { color: #2563eb; font-weight: bold; }
          .c-g { color: #059669; font-weight: bold; background: #d1fae5; padding: 2px 6px; border-radius: 4px; }
          .c-a { color: #d97706; font-weight: bold; background: #fef3c7; padding: 2px 6px; border-radius: 4px; }
          .c-r { color: #dc2626; font-weight: bold; background: #fee2e2; padding: 2px 6px; border-radius: 4px; }
          .f { background: #f8fafc; padding: 10px; text-align: center; font-size: 9px; color: #94a3b8; border-top: 1px solid #e2e8f0; }
        </style>
      </head>
      <body>
        <div class="w">
          <div class="h">
            <h1>Employee Attendance Summary</h1>
            <p>${periodLabel} • ${dateRange} • ${totalEmployees} Employees</p>
          </div>
          <div class="s">
            <span class="stat st-p">Present: ${totalPresent}</span>
            <span class="stat st-a">Absent: ${totalAbsent}</span>
            <span class="stat st-l">Late: ${totalLate}</span>
            <span class="stat st-lv">Leave: ${totalLeave}</span>
            <span style="font-size:10px;color:#64748b;margin-left:8px;">Avg. Attendance: <strong>${avgAttendance}%</strong></span>
          </div>
          <table>
            <tr><th>Name</th><th class="r">Dept</th><th class="r">Days</th><th class="r">Present</th><th class="r">Absent</th><th class="r">Late</th><th class="r">Leave</th><th class="r">%</th></tr>
            ${rows}
          </table>
          <div class="f">Generated by Pixenox • Employee Attendance Summary Report</div>
        </div>
      </body>
      </html>
    `.replace(/\s+/g, ' ').trim();

    try {
      const result = await hrService.sendCustomEmail({
        recipientEmail,
        subject: `[Employee Summary] ${periodLabel} — ${dateRange}`,
        html,
        type: 'SYSTEM_REPORT'
      });
      console.log("[emailService] Success queuing summary email:", result);
      return result;
    } catch (err) {
      console.error("[emailService] Error dispatching summary email:", err);
      throw err;
    }
  }
};